name: flutter_vk_sdk
description: VKontakte SDK for Flutter.
version: 0.1.0
author: Yury Smidovich <y.smidovich@gmail.com>
homepage: https://github.com/Stmol/flutter_vk_sdk

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: yury.smidovich.flutter_vk_sdk
    pluginClass: VkSdkPlugin
